import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";


export default function Home() {

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Index Of India</title>
          <meta name="description" content="Generated by create next app" />
          
        </Head>

        <h1 className={styles.title}>Index Of India</h1>
        <br />
        <div className={styles.img}>
        <Image
          src="/namaste.png"
          alt="Picture of the author"
          width={300}
          height={300}
          
        /></div>
        <br />
        <p>
          Click on All Articals button at navigation bar to see All Articals.
        </p>
        <br />
        <h1>About Us</h1>
        <p>
          i India Essay for Students and Children in English\nMay 21, 2020 by
          Prasanna\n\nEssay on India: India is the seventh-largest country by
          area and the second-most populous country in the world, situated in
          Asia. Three sides of India are surrounded by the Indian Ocean on the
          south, the Arabian Sea on the southwest, and by the Bay of Bengal on
          the southeast, it shares land borders with Pakistan, China, Nepal, and
          Bhutan to the north; and Bangladesh, and Myanmar to the east. The
          National animal of India is The Royal Bengal Tiger, National Bird of
          India is Peacock, National Fruit of India is Mango, National Flower of
          India is Lotus, and the name of the national anthem of In{" "}
        </p>

        <br />
        <br />
        <h1>Our Goal</h1>
        <p>
          i India Essay for Students and Children in English\nMay 21, 2020 by
          Prasanna\n\nEssay on India: India is the seventh-largest country by
          area and the second-most populous country in the world, situated in
          Asia. Three sides of India are surrounded by the Indian Ocean on the
          south, the Arabian Sea on the southwest, and by the Bay of Bengal on
          the southeast, it shares land borders with Pakistan, China, Nepal, and
          Bhutan to the north; and Bangladesh, and Myanmar to the east. The
          National animal of India is The Royal Bengal Tiger, National Bird of
          India is Peacock, National Fruit of India is Mango, National Flower of
          India is Lotus, and the name of the national anthem of In{" "}
        </p>
      </div>
    </>
  );
}
